<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录验证码</title>
</head>
<body class="background-image: linear-gradient(to top, #7028e4 0%, #e5b2ca 100%);">
    <h3>你好：</h3>
    <h4>你的账户正在登录eyi博客，这是您的验证码，请勿透漏给他人。</h4>
    <h4>请注意此验证码只有${expire}秒 ，请及时查看！</h4>
    <p style="color:blue;size: 20px">验证码为【 <span style="color:red;size: 15px">${captcha}</span>】</p>
    <h4>来自Eyi，请勿回复</h4>
</body>
</html>